version: "3"
services:

  app:
    build:
      context: .
    restart: unless-stopped
    ports:
      - 5001:5000
    command: ./start_flask.py
    volumes:
      - ./data:/app/data:ro
    environment:
      - "TZ=America/New_York"

  celery:
    build:
      context: .
    restart: unless-stopped
    command: ./start_celery.py
    devices:
      - /dev/bus/usb/005/020
    volumes:
      - ./data:/app/data
    environment:
      - "TZ=America/New_York"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data

volumes:
  redis-data:
