version: "3"
services:

  app:
    build:
      context: .
    restart: unless-stopped
    ports:
      - 5001:5000
    command: ./start_flask.py
    volumes:
      - ./data:/app/data:ro

  celery:
    build:
      context: .
    restart: unless-stopped
    command: ./start_celery.py
    devices:
      - /dev/bus/usb/005/005
    volumes:
      - ./data:/app/data

  redis:
    image: redis:6-alpine # TODO upgrade this?
    volumes:
      - redis-data:/data

volumes:
  redis-data:
