version: "3"
services:

  app:
    build:
      context: .
    restart: unless-stopped
    ports:
      - 5000:5000
    command: ./start_flask.py
    volumes:
      - ./data:/app/data:ro
    env_file:
      - .env

  celery:
    build:
      context: .
    restart: unless-stopped
    command: ./start_celery.py
    devices:
      - ${DEVICE}
    volumes:
      - ./data:/app/data
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data

volumes:
  redis-data:
